on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: Tiryoh
          password: ${{ secrets.CR_PAT }}
      - name: Make free space
        run: |
          df -h
          curl https://raw.githubusercontent.com/apache/flink/master/tools/azure-pipelines/free_disk_space.sh | bash
          sudo apt-get remove -y 'adoptopenjdk*'
          sudo apt clean
          docker rmi $(docker image ls --all --quiet)
          # https://github.com/actions/virtual-environments/issues/709#issuecomment-612569242
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      - name: Download the Docker image
        run: |
          curl -L '${{ secrets.IMAGE_URL }}' | docker load

      - name: Push the image
        run: docker push ghcr.io/tiryoh/jetson_image_core/image_core:jetpack4.4.1-sdkm1.3.1